// Autogenerated from Pigeon (v26.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace flutter_local_push_connectivity {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class LocalPushConnectivityHostApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


enum class NetworkType {
  kWifi = 0,
  // not support yet
  kCellular = 1
};

enum class ConnectType {
  kTcp = 0,
  kTlsTcp = 1,
  // not support yet
  kUdp = 2,
  // not support yet
  kTlsUdp = 3,
  kWebsocket = 4,
  kTlsWebsocket = 5,
  // not support yet
  kMqtt = 6
};


// Generated class from Pigeon that represents data sent in messages.
class LocalPushConnectivityModel {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit LocalPushConnectivityModel(
    const NetworkType& network_type,
    const ConnectType& connect_type);

  // Constructs an object setting all fields.
  explicit LocalPushConnectivityModel(
    const NetworkType& network_type,
    const ConnectType& connect_type,
    const std::string* host,
    const int64_t* port,
    const std::string* ssid);

  const NetworkType& network_type() const;
  void set_network_type(const NetworkType& value_arg);

  const ConnectType& connect_type() const;
  void set_connect_type(const ConnectType& value_arg);

  const std::string* host() const;
  void set_host(const std::string_view* value_arg);
  void set_host(std::string_view value_arg);

  const int64_t* port() const;
  void set_port(const int64_t* value_arg);
  void set_port(int64_t value_arg);

  // only for [NetworkType.wifi] & Platform.isIOS
  const std::string* ssid() const;
  void set_ssid(const std::string_view* value_arg);
  void set_ssid(std::string_view value_arg);

 private:
  static LocalPushConnectivityModel FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class LocalPushConnectivityHostApi;
  friend class PigeonInternalCodecSerializer;
  NetworkType network_type_;
  ConnectType connect_type_;
  std::optional<std::string> host_;
  std::optional<int64_t> port_;
  std::optional<std::string> ssid_;
};


class PigeonInternalCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;
 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;
};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class LocalPushConnectivityHostApi {
 public:
  LocalPushConnectivityHostApi(const LocalPushConnectivityHostApi&) = delete;
  LocalPushConnectivityHostApi& operator=(const LocalPushConnectivityHostApi&) = delete;
  virtual ~LocalPushConnectivityHostApi() {}
  virtual void Initialize(
    const LocalPushConnectivityModel& model,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void Connect(
    const LocalPushConnectivityModel& model,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void Disconnect(std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void Dispose(std::function<void(std::optional<FlutterError> reply)> result) = 0;

  // The codec used by LocalPushConnectivityHostApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `LocalPushConnectivityHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    LocalPushConnectivityHostApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    LocalPushConnectivityHostApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  LocalPushConnectivityHostApi() = default;
};
}  // namespace flutter_local_push_connectivity
#endif  // PIGEON_MESSAGES_G_H_
