name: melos_app

packages:
  - packages/**

scripts:
  build:
    exec: dart pub run build_runner build --delete-conflicting-outputs
    failFast: true
    packageFilters:
      dependsOn: build_runner
    description: build_runner build all modules.
  pigeon:
    exec: dart run pigeon --input pigeons/messages.dart
    failFast: true
    packageFilters:
      dependsOn: pigeon
    description: pigeon build all modules.